/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.netbeans.modules.bugtracking.gitlab.repository;

/**
 *
 */
public class GitLabRepositoryPanel extends javax.swing.JPanel {

    /**
     * Creates new form GitLabRepositoryPanel
     */
    public GitLabRepositoryPanel() {
        initComponents();

        // TODO: implement GraphQL and OAuth2 token
        graphqlRadioButton.setEnabled(false);
        oauth2RadioButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        apiBG = new javax.swing.ButtonGroup();
        authenticationBG = new javax.swing.ButtonGroup();
        nameLabel = new javax.swing.JLabel();
        serverUrlLabel = new javax.swing.JLabel();
        projectIdLabel = new javax.swing.JLabel();
        apiLabel = new javax.swing.JLabel();
        authenticationTokenLabel = new javax.swing.JLabel();

        org.openide.awt.Mnemonics.setLocalizedText(nameLabel, org.openide.util.NbBundle.getMessage(GitLabRepositoryPanel.class, "GitLabRepositoryPanel.nameLabel.text")); // NOI18N

        nameText.setText(org.openide.util.NbBundle.getMessage(GitLabRepositoryPanel.class, "GitLabRepositoryPanel.nameText.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(serverUrlLabel, org.openide.util.NbBundle.getMessage(GitLabRepositoryPanel.class, "GitLabRepositoryPanel.serverUrlLabel.text")); // NOI18N

        serverUrlText.setText(org.openide.util.NbBundle.getMessage(GitLabRepositoryPanel.class, "GitLabRepositoryPanel.serverUrlText.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(projectIdLabel, org.openide.util.NbBundle.getMessage(GitLabRepositoryPanel.class, "GitLabRepositoryPanel.projectIdLabel.text")); // NOI18N

        projectIdText.setText(org.openide.util.NbBundle.getMessage(GitLabRepositoryPanel.class, "GitLabRepositoryPanel.projectIdText.text")); // NOI18N
        projectIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectIdTextActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(apiLabel, org.openide.util.NbBundle.getMessage(GitLabRepositoryPanel.class, "GitLabRepositoryPanel.apiLabel.text")); // NOI18N

        apiBG.add(rest4RadioButton);
        rest4RadioButton.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(rest4RadioButton, org.openide.util.NbBundle.getMessage(GitLabRepositoryPanel.class, "GitLabRepositoryPanel.rest4RadioButton.text")); // NOI18N

        apiBG.add(graphqlRadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(graphqlRadioButton, org.openide.util.NbBundle.getMessage(GitLabRepositoryPanel.class, "GitLabRepositoryPanel.graphqlRadioButton.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(authenticationTokenLabel, org.openide.util.NbBundle.getMessage(GitLabRepositoryPanel.class, "GitLabRepositoryPanel.authenticationTokenLabel.text")); // NOI18N

        authenticationBG.add(oauth2RadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(oauth2RadioButton, org.openide.util.NbBundle.getMessage(GitLabRepositoryPanel.class, "GitLabRepositoryPanel.oauth2RadioButton.text")); // NOI18N

        authenticationBG.add(personalAccessRadioButton);
        personalAccessRadioButton.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(personalAccessRadioButton, org.openide.util.NbBundle.getMessage(GitLabRepositoryPanel.class, "GitLabRepositoryPanel.personalAccessRadioButton.text")); // NOI18N

        personalAccessText.setText(org.openide.util.NbBundle.getMessage(GitLabRepositoryPanel.class, "GitLabRepositoryPanel.personalAccessText.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(serverUrlLabel)
                    .addComponent(nameLabel)
                    .addComponent(projectIdLabel)
                    .addComponent(apiLabel)
                    .addComponent(authenticationTokenLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rest4RadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(graphqlRadioButton)
                        .addContainerGap())
                    .addComponent(nameText)
                    .addComponent(serverUrlText)
                    .addComponent(projectIdText)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(oauth2RadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(personalAccessRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(personalAccessText, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serverUrlLabel)
                    .addComponent(serverUrlText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectIdLabel)
                    .addComponent(projectIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apiLabel)
                    .addComponent(rest4RadioButton)
                    .addComponent(graphqlRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(authenticationTokenLabel)
                    .addComponent(oauth2RadioButton)
                    .addComponent(personalAccessRadioButton)
                    .addComponent(personalAccessText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void projectIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectIdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectIdTextActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup apiBG;
    private javax.swing.JLabel apiLabel;
    private javax.swing.ButtonGroup authenticationBG;
    private javax.swing.JLabel authenticationTokenLabel;
    final javax.swing.JRadioButton graphqlRadioButton = new javax.swing.JRadioButton();
    private javax.swing.JLabel nameLabel;
    final javax.swing.JTextField nameText = new javax.swing.JTextField();
    final javax.swing.JRadioButton oauth2RadioButton = new javax.swing.JRadioButton();
    final javax.swing.JRadioButton personalAccessRadioButton = new javax.swing.JRadioButton();
    final javax.swing.JTextField personalAccessText = new javax.swing.JTextField();
    private javax.swing.JLabel projectIdLabel;
    final javax.swing.JTextField projectIdText = new javax.swing.JTextField();
    final javax.swing.JRadioButton rest4RadioButton = new javax.swing.JRadioButton();
    private javax.swing.JLabel serverUrlLabel;
    final javax.swing.JTextField serverUrlText = new javax.swing.JTextField();
    // End of variables declaration//GEN-END:variables
}
